#!/usr/bin/env node
/* MedBank · viz-training · coverage
 *
 * Answers one question, from the curriculum rather than from anybody's memory: WHICH DIAGRAMS SHOULD
 * EXIST, AND WHICH ONES DO?
 *
 * "Every possible diagram" is unbounded — you can always draw one more. So this report does not use
 * that as its standard. It uses the one the curriculum already states: every structure in
 * CURRICULUM.json carries a `views` list naming the view TYPES it needs — location, cross_section,
 * mechanism, vasculature and so on. That list is the contract. A structure is covered when a scene
 * exists for it and that scene has a view of every type its curriculum entry asks for.
 *
 * That is worth saying plainly because it reframes the work: the corpus is not short of diagrams
 * inside the scenes it has (they average seven views each). It is short of SCENES. Coverage is a
 * question about the gaps between scenes, not about the depth within them.
 *
 * Run: node tools/coverage.mjs          → rewrites viz-training/COVERAGE.md
 *      node tools/coverage.mjs --queue  → also prints the missing structures as queue-ready JSON
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const slug = s => String(s).replace(/[&/()]/g, ' ').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const curriculum = JSON.parse(readFileSync(join(ROOT, 'CURRICULUM.json'), 'utf8'));
const scenes = {};
for (const f of readdirSync(join(ROOT, 'scenes'))) {
  if (!f.endsWith('.json') || f === 'index.json') continue;
  try { scenes[f.slice(0, -5)] = JSON.parse(readFileSync(join(ROOT, 'scenes', f), 'utf8')); } catch {}
}

/* A scene id is course__topic__structure, but topic slugs have drifted ("Arm (Brachium)" became
   "arm"), so fall back to matching on the structure slug within the same course before declaring
   anything absent. Five gross structures look missing on an exact match and are not. */
function sceneFor(course, topic, name) {
  const exact = `${course}__${slug(topic)}__${slug(name)}`;
  if (scenes[exact]) return [exact, scenes[exact]];
  const tail = '__' + slug(name);
  const hit = Object.keys(scenes).find(k => k.startsWith(course + '__') && k.endsWith(tail));
  return hit ? [hit, scenes[hit]] : [null, null];
}

const out = [];
const P = s => out.push(s);
const totals = { structures: 0, withScene: 0, declared: 0, covered: 0, views: 0, absent: [] };
const suspended = {};

P('# MedBank · viz-training · COVERAGE');
P('');
P('_Generated by `tools/coverage.mjs`. Do not hand-edit — rerun it._');
P('');
P('**What "covered" means here.** Not "every diagram anyone could draw" — that has no end. Every');
P('structure in `CURRICULUM.json` declares the view TYPES it needs. That declaration is the contract,');
P('and a structure is covered when a scene exists for it carrying a view of each declared type.');
P('');

for (const [ck, cv] of Object.entries(curriculum.courses)) {
  if (cv.suspended) suspended[ck] = cv.suspended;
  P(`## ${cv.name || ck}`);
  P('');
  if (cv.suspended) { P(`> **SUSPENDED.** ${String(cv.suspended).split('.')[0]}.`); P(''); }
  P('| topic | structure | declared views | scene | status | missing |');
  P('|---|---|---|---|---|---|');
  for (const t of cv.topics) {
    for (const s of t.structures) {
      totals.structures++;
      const want = s.views || [];
      totals.declared += want.length;
      const [id, scene] = sceneFor(ck, t.topic, s.name);
      if (!scene) {
        totals.absent.push({ course: ck, topic: t.topic, structure: s.name, views: want, modes: s.preferred_modes || [] });
        P(`| ${t.topic} | ${s.name} | ${want.join(', ') || '—'} | **none** | — | all ${want.length} |`);
        continue;
      }
      totals.withScene++;
      const have = (scene.views || []).map(v => v.mode);
      totals.views += (scene.views || []).length;
      const missing = want.filter(w => !have.includes(w));
      totals.covered += want.length - missing.length;
      P(`| ${t.topic} | ${s.name} | ${want.join(', ') || '—'} | ${(scene.views || []).length} views | ${scene.status} | ${missing.join(', ') || '—'} |`);
    }
  }
  P('');
}

P('## Where the gap actually is');
P('');
P(`- **${totals.structures}** structures in the curriculum, declaring **${totals.declared}** view-slots between them.`);
P(`- **${totals.withScene}** have a scene. Those scenes carry **${totals.views}** authored views — an average of **${(totals.views / Math.max(totals.withScene, 1)).toFixed(1)} per structure**.`);
P(`- **${totals.covered}/${totals.declared}** declared view-slots are covered.`);
P(`- **${totals.absent.length}** structures have no scene at all. That is the whole gap.`);
P('');
P('The corpus is not thin inside the scenes it has — seven views per structure is already more than');
P('most atlases give a topic. It is missing whole structures. So the useful question is never "should');
P('we add more diagrams to this scene", it is "which structures still have nothing".');
P('');
P('### Structures with no scene');
P('');
const byCourse = {};
for (const a of totals.absent) (byCourse[a.course] ||= []).push(a);
for (const [ck, list] of Object.entries(byCourse)) {
  const byTopic = {};
  for (const a of list) (byTopic[a.topic] ||= []).push(a.structure);
  P(`**${ck} — ${list.length}**`);
  P('');
  for (const [t, names] of Object.entries(byTopic)) P(`- ${t}: ${names.join(', ')}`);
  P('');
}
if (Object.keys(suspended).length) {
  P('### Suspended courses');
  P('');
  for (const [k, why] of Object.entries(suspended)) P(`- **${k}** — ${why}`);
  P('');
}

writeFileSync(join(ROOT, 'COVERAGE.md'), out.join('\n') + '\n');
console.log(`COVERAGE.md written · ${totals.structures} structures · ${totals.withScene} with a scene · ${totals.absent.length} with none · ${totals.covered}/${totals.declared} declared views covered`);

if (process.argv.includes('--queue')) {
  console.log(JSON.stringify(totals.absent.map(a => ({
    id: `${a.course}__${slug(a.topic)}__${slug(a.structure)}`,
    kind: 'scene', status: 'todo',
    note: `NO SCENE EXISTS. Curriculum declares views: ${a.views.join(', ') || '(none)'}; preferred modes: ${a.modes.join(', ') || '(none)'}. This is authoring plus building, not building alone.`
  })), null, 2));
}
