/* ROUND-3 REVIEW · writes its verdict THROUGH tools/queue-set.mjs (never by hand).
   Spawns the tool with an argv array, so nothing passes through a shell and no quoting can corrupt it. */
import { spawnSync } from 'child_process';
import { readFileSync } from 'fs';
import path from 'path';

const HERE = process.argv[2];                       // viz-training dir
const QUEUE = path.join(HERE, 'BUILD-QUEUE.json');
const ID = 'embryology__cardiovascular-development__cardiac-looping';
const q = JSON.parse(readFileSync(QUEUE, 'utf8'));
const it = q.items.find(i => i.id === ID);
if (!it) { console.error('item not found'); process.exit(2); }
const round2Findings = it.findings;
if (!Array.isArray(round2Findings)) { console.error('unexpected findings shape'); process.exit(2); }

const FINDINGS = [
"1. THE ATRIUM AND THE SINUS VENOSUS FINISH ENTIRELY ON THE EMBRYO'S LEFT. The build task declared this itself and could not solve it out; it is confirmed, and the BOUNDING BOX makes it worse than the centroid the builder reported. Measured on real mesh vertices at t=1 (+x = LEFT): atrium x spans +0.151 to +2.017 — it NEVER REACHES THE MEDIAN PLANE, let alone straddles it; sinus x spans -0.085 to +1.716, 95.3% of its width on the left. Centroids atrium +1.101, sinus +0.729 (the builder's centreline figures were +1.14 and +0.66). Why it is a teaching error and not a cosmetic one: the common atrium at day 28 straddles the midline, and the sinus venosus is the RIGHT-sided inflow whose right horn becomes the sinus venarum — the smooth posterior wall of the right atrium and the reason SVC and IVC drain where they do. A student who learns this picture puts the systemic venous inflow on the left. Test J (|atrium x| small) and K (|sinus x| small) exist in the builder's own notes and both FAIL.",

"2. THE ATRIA ARE NOT ABOVE THE VENTRICLES — NEW, AND NOTHING IN THE TEST SET CONSTRAINS IT. At t=1 the atrium spans y -2.714 to -0.514 (height 2.200) and the ventricle spans y -3.100 to -0.563 (height 2.538). THE OVERLAP IS 2.152, WHICH IS 97.8% OF THE ATRIUM'S OWN VERTICAL EXTENT. Centroid separation D = +0.351, i.e. 16% of the atrium's height. Test D asks only 'atrium y - ventricle y > 0' and +0.351 satisfies it, so the model asserts the relation on every build while the picture does not show it. This is the THIRD movement, which is the entire subject of view 5 ('Movement three — the atria climb up behind') and the second line of view 6's three-sentence exam drill ('atria side by side behind and above them'). For contrast the DORSAL half of the same claim is legible and fine: C = -0.80 with only 58% z-overlap. It is specifically the vertical separation that is missing. Note also that in the world frame the atrium and sinus DESCEND between t=0 and t=1 (atrium y -1.060 to -1.548, sinus -2.249 to -2.702) while the venous pole is nailed at y -2.887, so on screen nothing climbs; the relation only improves because the ventricle descends faster.",

"3. THE VENTRICLE FINISHES ON THE MEDIAN PLANE, NOT TO THE LEFT — TEST I PASSES ON THE SIGN AND THE PICTURE DOES NOT. Ventricle centroid x = +0.070 on a chamber 1.329 wide: FIVE PER CENT of its own width. Round 2 wrote I as 'ventricle centroid x > 0' and the round-2 rework solved to +0.070, which satisfies it exactly and invisibly. View 4 says 'the primitive ventricle moves backwards and to the left'; views 6 and 8 depend on the future left ventricle being visibly left-posterior, because that is what makes view 8's 'the morphological right ventricle on the left' a legible contrast rather than a caption. A student sees a ventricle in the middle. THIS IS THE SAME FAILURE MODE ROUND 2 FOUND TWICE (finding 2, a test that did not test its own `must` string; finding 4, a test that locked in a defect) NOW RECURRING IN A TEST ROUND 2 ITSELF WROTE. See standards_gap_round_3: the fix is a magnitude floor, not another sign test.",

"4. THE SINUS VENOSUS IS AN OPEN PIPE AT ITS CAUDAL END, AND IT IS VISIBLE IN VIEWS 3 AND 4. sweptShell() closes every segment with ANNULAR END CAPS, and OVERLAP = 0.006 hides the caps at the four internal waists — but the tube has TWO TERMINAL ends with no neighbour to hide behind. gaps[10] records that view 9 was tried from ABOVE and rejected because it 'looks straight down the truncus and shows its open lumen — the one thing RENDER-STANDARD says must never be visible'. The caudal end of the SINUS has exactly the same cap and was never worked around: it is plainly visible from the ANTERIOR camera at stage _b, which is the camera and the stage that views 3 and 4 both use. Wall ring and lit inner surface are unambiguous in _review-2026-09-10-r3-cardiac-looping/crop-sinus-b.png. The veins cross the opening without plugging it. This is the same defect at the other end of the same tube, avoided at one end by choosing a camera and left exposed at the other — the unlisted place. FIX: do not solve it with a camera. Either carry the sinus caudally into the vein confluence so the veins close it, or cap the terminal ends with a rounded dome rather than an annulus.",

"5. THE MEDIAN-PLANE REFERENCE IS 96.5% OCCLUDED IN THE ONLY VIEW THAT USES IT. The midline is a rod of RADIUS 0.030 plus three ventral ticks that reach only z = +1.15, while the heart's ventral surface at t=1 reaches z = +1.684 — so the rod lies BEHIND the ventricle and bulbus from the anterior camera. Measured by differencing view 9's own camera with and without midline:true — midline pixels if nothing occluded it 3,525; midline pixels ACTUALLY VISIBLE 125; that is 0.081% of the subject's 154,711 pixels. The reference was added in round 1 (finding 12) specifically so that 'mirror image about the median plane' would be a visible claim rather than a caption, and view 9 HIGHLIGHTs it at intensity 0.6. It does not survive its own view. FIX: draw the plane as a translucent quad in the median plane, or bring the ticks forward past z = +1.7 and thicken the rod, and re-measure the visible pixel count rather than assuming.",

"6. VIEWS 3 AND 4 NARRATE TWO SEQUENTIAL MOVEMENTS OVER ONE FROZEN STAGE, SO NEITHER MOVEMENT IS VISIBLE AS A MOVEMENT. Both views draw stage _b (t = 0.65) with an IDENTICAL structure set and an identical camera, differing only in which structure is highlighted. They pass the no-duplicate-frame rule as written, and they are not pixel-identical. But all four Gaussian bends grow together with t, so NO value of t separates movement one from movement two: at t = 0.65 the ventricle has already swung dorsally and left whatever view 3's title says, and by stage _c all three movements are complete. A student told 'the first movement is the one that names the loop' is looking at a picture in which the second and third have already happened. gaps[2] declares the per-structure-t mechanism but not this consequence. FIX, and it does not need the engine: give the four bends STAGGERED ONSETS in t so that the bulboventricular bend leads and the sinoatrial bend follows, then add a stage between _a and _b. Do not fix it by re-pointing _b — that was tried in round 1 and the movements still coincide.",

"7. STATED POSITIVELY — ROUND 2'S FOUR FINDINGS ARE ALL GENUINELY FIXED, RE-VERIFIED WITHOUT THE BUILDER'S PROVERS. The build task asked for exactly this ('prove-mirror-chirality.mjs is not independent evidence — I wrote both the fix and its prover'), so it was done in a harness written for this review. FINDING 1, the mirror: every vertex of all ELEVEN parts matches a true reflect-X at 1.0000 and rot-Y-180 at 0.0000-0.0020, with identical vertex counts; the signed volume recomputed here from MESH centroids (not the centreline tetrahedron mirrorProof() uses) is D -0.05029 / L +0.05029, ratio exactly -1.0000, where round 2 measured +1.0000. In the picture, view 9's mirror against view 6's D-loop is a clean left-right flip at the same size, against round 2's measured 79% of width. FINDINGS 3 AND 4: all nine acceptance tests pass and are stable across integration density — nseg 140/300/600 agree to 0.003, worst drift 300->600 = 0.003, and the builder's shipped numbers reproduce exactly. FINDING 5: peri_a on view 1 and peri_c on view 6, both present. FINDING 2 was the reviewer's own correction and is preserved. Finding 6 (cross-item) is dissolved as the builder said.",

"8. ANSWERING THE BUILD TASK'S DIRECT QUESTION, BECAUSE IT ASKED THE REVIEW TO DECIDE AND IT WAS RIGHT NOT TO DECIDE ALONE. The question was: 'whether the fix is a richer curvature model (a bend whose plane varies along its own width, or a fifth bend) or whether test I should be weakened instead'. THE ANSWER IS: DO NOT WEAKEN I, ENRICH THE MODEL. The anatomy is determinate — the future left ventricle finishes left-posterior, the common atrium straddles the midline, the atria finish above the ventricles — so every one of findings 1, 2 and 3 has a correct answer that geometry can express, and weakening a test to fit a curvature model is the standard lowering itself to let the item pass. The builder's own diagnosis is almost certainly right: four Gaussian bends each carrying ONE plane cannot control the atrium's lateral position independently of the ventricle's, and that is a missing degree of freedom rather than a failed search. FINDINGS 1, 2 AND 3 ARE ONE SOLVE, NOT THREE PIECES OF WORK: add J (|atrium x| <= 0.35), K (|sinus x| <= 0.45) and a strengthened D and I per standards_gap_round_3, give the model the extra freedom first, and solve once. Findings 4, 5 and 6 are independent of that solve and can be done in any order.",
];

const REVIEW_METHOD = [
"ROUND 3. Reviewer did not build this scene and did not use the build task's provers, which the build task explicitly asked for.",
"OWN ORDER FIRST, per REVIEW-TASK-PROMPT. Before opening BUILD-LOG.md or built_notes, three checks were fixed from the scene and the curriculum entry alone: (1) whether +mirror is a true reflection or a rotation, since views 8 and 9 both stand on it; (2) whether t=0.65 is a defensible mid-loop, since gaps[] admits its previous justification was withdrawn as false; (3) whether every stage's structures are stage-matched, since arches carry _a/_b/_c and veins carry only _c. Check 3 was MINE and it was WRONG in an instructive way — the veins are byte-identical at every t (same 11,136 vertices, same centroid, same hash), so veins_c really is correct at every stage and gaps[5]'s claim is true. It is recorded because a reviewer's disproved suspicion is worth as much to the next run as a confirmed one. Checks 1 and 2 landed on round 2's findings 1 and 3, both verified fixed.",
"THE DEFECTS THIS ROUND CAME FROM THE PLACES THE NOTES DO NOT MENTION. Findings 2, 4, 5 and 6 are in the vertical distribution, the terminal end caps, the median-plane rod and the view-to-stage mapping — none of which appears in built_notes, findings_for_review or any previous round's findings.",
"MECHANICAL. Own harness: model + render-kit + three.js loaded by <script src> from a static server into headless Chromium. Builds at t = 0, 0.2, 0.4, 0.6, 0.65, 0.8, 1.0 with no throw. Console clean after this round's correction (a) — it was NOT clean before it. All 45 scene refs name one of the 11 keys the model builds; all 11 are named by a view or declared in gaps[]. Normals measured per mesh against that mesh's own centroid, with outline meshes excluded because they carry no normal attribute: myocardial segments 0.512-0.517, the documented thick-walled-shell figure; veins 0.94-1.00; arches 0.61-1.00; midline and pericardium 1.00. No consecutive view pair shares the structure-set + highlight + rotation + section tuple. No CDN import; no local reimplementation of winding, normals, colour or silhouettes.",
"ANATOMICAL, IN THE PROTOCOL ORDER. The rendered picture first, at all three stages, anterior and lateral and from below and behind and mirrored, before the scene JSON and before the source. Findings 1, 2, 4 and 5 were seen in the picture and then measured; the source was opened afterwards only to locate what the picture had already shown — sweptShell's annular caps for finding 4, the 0.030 rod for finding 5, the shared bend schedule for finding 6.",
"ONE FALSE ALARM, RECORDED SO THE NEXT RUN DOES NOT REPEAT IT. acceptance()'s parameter is NSEG, not t. Calling acceptance(1) — which is what the built_notes' phrasing invites — integrates the centreline with a single segment and returns confident-looking numbers at 1e-16 reporting D, G and I FAILING. It was nearly filed as a CRITICAL finding against a model whose tests all pass. It is now a thrown error naming the parameter; see corrected_this_round_3 (c).",
];

const CORRECTED = [
"(a) MODEL, models3d/cardiac-looping.js — the mirror chirality probe warned on its own degenerate case. At t = 0 the tube is straight, the sinus-atrium-ventricle-bulbus centroids are coplanar, the signed volume is exactly 0 and the ratio is 0/0; the guard treated CANNOT MEASURE as MEASURED AND WRONG and fired on every t=0 mirror build, which is what cost tools/test-per-view-t.mjs its console-clean check while testing a different item. Verified at t = 0/0.2/0.4/0.6/0.65/0.8/1: the ratio is null only at t = 0 and is exactly -1.000 at every other t. It now reports not-measurable and does not warn. Console is now clean at every t and on the mirror build. This closes the finding the engine__per-view-t review raised on this item without changing its status.",
"(b) MODEL — the dorsal mesocardium ignored its own layer flag. The guard read `opts.mesocardium !== false`, making it the ONE optional layer that was on unless switched off, while endocardium, pericardium and midline are all opt-in and FULL declares all four alike. build(t, {}) returned a mesocardium nobody asked for. Invisible in the player, because the provider builds with FULL and slices by key — but every DIRECT render carried it, including the build task's own stage proofs: in tools/render-cardiac-looping.mjs the plain stages pass {} and the -meso stages pass {mesocardium:true}, so the pair that was meant to show the sheet against its absence differed only by the midline rod. Now opt-in, like the other three. Re-verified: build(1,{}) no longer emits it, build(1,{mesocardium:true}) and FULL still do.",
"(c) MODEL — acceptance(nseg) accepted a t and returned a false failure. Added a guard that throws a message naming the parameter for anything below 8 segments. See review_method_round_3.",
"(d) SCENE — corrected a false measurement claim in gaps[]. It read that at day 28 the mesocardium is 'two small reflections almost entirely hidden behind the heart'. Measured on the built geometry at t=1 the two cuffs span 2.10 in x and 2.29 in y on a heart 3.27 x 3.19 x 2.49, and their dorsal edge stands 0.74 clear behind the dorsal-most point of the atrium — in the LATERAL camera, which is view 5's camera, it is a conspicuous wing. It stays out of the player because every view from 3 onwards opens with HIDE_STRUCTURE *, not because it is small. Corrected in place with the measurement, so a future view sizes it against the number rather than the note.",
"(e) SCENE — recorded (a), (b) and (c) in gaps[] and stamped provenance.corrected_at_round_3 / corrected_by_round_3 / correction_note_round_3.",
"NO GEOMETRY AND NO NARRATION WERE CHANGED. All nine acceptance tests still pass at nseg 140/300/600 after the corrections, with the same numbers; the reflection still matches reflect-X at 1.0000 on all eleven parts; validate-scenes is 142/142.",
];

const STANDARDS_GAP =
"THE STANDARD HAS A GAP AND THIS IS THE THIRD ROUND IN A ROW IT HAS COST SOMETHING. Round 2 finding 2: a test whose implementation did not match its own `must` string. Round 2 finding 4: a test that asserted a defect and so locked it in. Round 3 finding 3: a test that is CORRECT and asserts the right relation, and is satisfied by a value so small the claim is invisible — ventricle x = +0.070 on a chamber 1.329 wide passes 'ventricle centroid x > 0' at 5% of its own width. Finding 2 is the same shape: D = +0.351 passes 'atrium y - ventricle y > 0' while 97.8% of the atrium's vertical extent still overlaps the ventricle's. PROPOSED RULE, for RENDER-STANDARD and for the acceptance-test convention generally: A SIGN TEST ON A SPATIAL RELATION IS NOT A TEST. Every acceptance assertion of the form 'A is left of / above / behind B' must carry a MAGNITUDE FLOOR expressed as a fraction of the relevant extent of the structures being compared — as a starting figure, a separation of at least 35% of the mean of the two structures' extents along that axis, so that the relation is legible in the picture and not merely true in the arithmetic. Sign-only tests should be written as `> 0.35 * meanExtent`, not `> 0`, and any existing sign test should be read as UNPROVEN until it carries a floor. The deeper rule, which is what the three rounds actually demonstrate: A TEST THAT CAN BE SATISFIED WITHOUT THE PICTURE CHANGING IS NOT MEASURING WHAT THE NARRATION CLAIMS. The narration is about what a student can SEE; the tests should be too. Second, smaller gap: the review standard says 'console clean — no errors, no warnings' but nothing says a self-check must distinguish CANNOT MEASURE from MEASURED AND WRONG. Corrected here as (a); the rule is that a probe with a degenerate case must report the degeneracy, because a warning that is a known false alarm trains every future run to ignore the channel it is printed on.";

const ESCALATION_BASIS =
"NOT ESCALATED, AND THIS IS THE FIRST NON-CONVERGING ROUND. open_findings_by_round is [13, 4, 6]: the count ROSE, 4 to 6. Round 2's own escalation_basis predicted this rule would be tested here and set the bar: 'If round 3 closes with 4 or more open findings, that is the first flat round and round 4 would be the escalation.' The rule requires as-many-or-more TWICE IN A ROW, so round 3 is the first and round 4 is the decision point. IF ROUND 4 CLOSES WITH 6 OR MORE OPEN FINDINGS, ESCALATE — do not spend a fifth round. THE CONTEXT THE NEXT RUN NEEDS, stated without softening the rule: all four of round 2's findings are verified CLOSED, including the critical one, and all six open findings are NEW. The count rose because round 3 looked at the poles, the median-plane reference, the vertical distribution and the layer flags, which nobody had looked at before — not because round 2's fixes failed. That is thoroughness, not a loop. But it is also exactly what the flat-round rule is there to catch if it repeats, so the next reviewer should apply the rule as written and not re-argue this paragraph. NO FINDING THIS ROUND IS A DECISION RATHER THAN A DEFECT: findings 1, 2, 3, 4, 5 and 6 all have a determinate correct answer that geometry can express, and finding 8 answers the one question the build task escalated to the review (do not weaken test I). ONE DECISION-SHAPED ITEM EXISTS AND IS DELIBERATELY NOT A FINDING — see decision_for_frank — because it blocks nothing and falsifies no narration; it is raised in the review's reply instead so that it reaches a person without stopping the loop.";

const DECISION_FOR_FRANK =
"NOT BLOCKING, NOT A FINDING, AND NOT ESCALATED — but it is a teaching decision that only you can make, so it is recorded here and raised in the review's reply. The build task measured, and this review confirms, that PEAK CROWDING OF THE HEART INSIDE THE PERICARDIAL SAC IS AT MID-LOOP, NOT AT DAY 28: t = 0.65 measures 84% width and 69% depth of the sac against 75% and 57% at t = 1, because the sac keeps widening on its own schedule after the loop has stopped bulging. Views 1 and 6 show the sac at day 23 and day 28, so the two frames a student compares do not bracket the tightest moment. View 1's narration — the mechanical premise of the whole scene — is 'it is elongating faster than the pericardial cavity around it'. THE QUESTION: is the intended teaching that day 28 is the tightest moment (in which case the sac's width schedule needs re-examining), or that the crowding peaks during the loop and eases as the sac catches up (in which case the sac belongs on a mid-loop view too, and the narration could say so)? Both are defensible and the geometry cannot choose. Nothing is blocked either way — no view currently makes a false claim about it.";

const ACCEPTANCE_R3 = {
  why: "Round 3 does not replace the round-2 amendments; A, B', C, D, E, F, G, H, H65, I and M all pass and were reproduced independently at nseg 140/300/600. These are the ADDITIONS the round-3 findings require, and they are the ones to solve against together with the existing set. Per finding 8, do NOT weaken I to make this easier.",
  axes: "+x = embryo LEFT, -x = RIGHT, +y = CRANIAL, +z = VENTRAL",
  additions: [
    { id: "J", says: "the common atrium STRADDLES the median plane", must: "the atrium's mesh bounding box must contain x = 0, and |atrium centroid x| <= 0.35",
      currently: "box +0.151 to +2.017 — does not contain x = 0. Centroid +1.101. FAILS. See finding 1." },
    { id: "K", says: "the sinus venosus is not a left-sided structure", must: "|sinus centroid x| <= 0.45",
      currently: "+0.729, with 95.3% of its width left of the median plane. FAILS. See finding 1." },
    { id: "D-prime", replaces: "D", says: "the atria finish VISIBLY above the ventricles, not merely above by sign",
      must: "atrium y - ventricle y >= 0.35 * mean(atrium y-extent, ventricle y-extent), i.e. >= 0.83 at current chamber sizes",
      currently: "+0.351 against 2.369 mean extent = 0.15 of it, and 97.8% of the atrium's height still overlaps the ventricle's. FAILS. See finding 2 and standards_gap_round_3." },
    { id: "I-prime", replaces: "I", says: "the primitive ventricle finishes VISIBLY left of the median plane",
      must: "ventricle centroid x >= 0.35 * ventricle x-extent, i.e. >= 0.47 at the current chamber width of 1.329",
      currently: "+0.070, which is 5% of its own width. Passes I as written and fails I'. See finding 3." },
    { id: "N", says: "no terminal end cap of the myocardial tube is visible from any camera a view uses",
      must: "the caudal end of the sinus and the cranial end of the truncus must be closed by a dome or occluded by a neighbouring structure, not by an annular cap",
      currently: "the sinus's caudal annulus is visible from the anterior camera at stage _b, which views 3 and 4 both use. FAILS. See finding 4." },
    { id: "O", says: "the median-plane reference is actually visible in the view that uses it",
      must: "in view 9's camera, midline pixels surviving occlusion >= 1.5% of the subject's pixels",
      currently: "125 px of 154,711 = 0.081%, with 96.5% of the rod occluded. FAILS. See finding 5." },
  ],
};

const args = [
  ID,
  '--json', 'findings_round_2=' + JSON.stringify(round2Findings),
  '--json', 'findings=' + JSON.stringify(FINDINGS),
  '--json', 'review_method_round_3=' + JSON.stringify(REVIEW_METHOD),
  '--json', 'corrected_this_round_3=' + JSON.stringify(CORRECTED),
  '--json', 'acceptance_round_3=' + JSON.stringify(ACCEPTANCE_R3),
  '--json', 'open_findings_by_round=' + JSON.stringify([13, 4, 6]),
  '--set', 'standards_gap_round_3=' + STANDARDS_GAP,
  '--set', 'escalation_basis=' + ESCALATION_BASIS,
  '--set', 'decision_for_frank=' + DECISION_FOR_FRANK,
  '--set', 'reviewed_at=2026-09-10T17:56:00Z',
  '--set', 'reviewed_by=model3d REVIEW task, round 3 — cloud run with the medbank folder attached; did not build this scene and did not use the build task’s provers',
  '--set', 'review_artifacts_round_3=viz-training/_review-2026-09-10-r3-cardiac-looping/ — MEASUREMENTS.md (every number in these findings, with the method), the four review harnesses that produced them (probe.mjs, probe2.mjs, render.mjs, vis.mjs) and their raw output (probe.json, probe2.json), crop-sinus-b.png (finding 4, the open lumen), m9-all.png vs m9-nomid.png (finding 5, the occluded midline), and the stage renders. Round 1 and round 2 artefacts in _review-2026-09-10/ and _review-2026-09-10-r2/ are unsuperseded.',
  '--bump', 'review_rounds',
  '--status', 'changes-requested',
];
const r = spawnSync('node', [path.join(HERE, 'tools', 'queue-set.mjs'), ...args], { encoding: 'utf8' });
process.stdout.write(r.stdout || '');
process.stderr.write(r.stderr || '');
process.exit(r.status === null ? 1 : r.status);
